import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd,        
           cwd + 'include']

src += Glob('app/*.c', 'platform/*.c')

objs = DefineGroup('rpmsg-port', src, depend = ['PKG_USING_RPMSG_LITE'], CPPPATH = CPPPATH)

Return('objs')
